version: "3.9"
services:
  beancount-node-server:
    container_name: beancount-node-server
    image: beancount-node-server:latest
    ports:
      - "3001:3001"
    volumes:
      - "/data/beancount:/beancount"